openapi: 3.0.0
info:
  title: GitHub API Collection
  version: 1.0.0
paths:
  /user/repos:
    post:
      summary: Create a New Repository
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: my-new-repo
                description:
                  type: string
                  example: My new repository
      responses:
        '201':
          description: Repository created successfully
          content:
            application/json:
              example:
                name: my-new-repo
                description: My new repository

