{
	"info": {
		"_postman_id": "e9fa97b1-7710-42ce-a492-63bcb7bacb63",
		"name": "✅ Assignment #5",
		"description": "## Instructions for Assignment #5\n\n1. **Get the challenge:** Fork the parent collection to your own public workspace.\n2. **Read the instructions:** You will find the tasks you need to complete below.\n3. **Verify your solution:** Select the second folder `Check your solution` and follow the instructions in the documentation to validate your solution.\n    \n\n## Tasks\n\n### Task 1\n\nCreate a public GitHub project and configure a GitHub Actions workflow. Ensure the workflow is stored in the following location:\n\n```\n.github/workflows/postman.yml\n\n```\n\n### Task 2\n\nOnce you have created the Postman workflow, ensure that the Postman collection run is successful.",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
		"_exporter_id": "15474556",
		"_collection_link": "https://www.postman.com/maintenance-operator-91826831/workspace/my-workspace/collection/15474556-e9fa97b1-7710-42ce-a492-63bcb7bacb63?action=share&source=collection_link&creator=15474556"
	},
	"item": [
		{
			"name": "Check your solution",
			"item": [
				{
					"name": "Verify your work",
					"event": [
						{
							"listen": "test",
							"script": {
								"exec": [
									"pm.test(\"If you have any failures, review the failed test results or ask for support in the community forum. Remember to save your changes if you update the collection.\", () => {",
									"});",
									"",
									"pm.test(\"Status code is 200\", () => {",
									"    pm.response.to.have.status(200);",
									"});",
									"",
									"pm.test(\"Contains Postman workflow\", () => {",
									"    const url = pm.variables.replaceIn(`{{githubProjectUrl}}/blob/main/.github/workflows/postman.yml`);",
									"",
									"    pm.expect(url).to.include('github.com');",
									"",
									"    pm.sendRequest(url, function (err, response) {",
									"        pm.expect(response.code).to.equal(200);",
									"    });",
									"});",
									"",
									"pm.test(\"Postman workflow uses Postman CLI\", () => {",
									"    const url = pm.variables.replaceIn(`{{githubProjectUrl}}/blob/main/.github/workflows/postman.yml`);",
									"",
									"    pm.sendRequest(url, function (err, response) {",
									"        console.log(response);",
									"        pm.expect(response.text()).to.include(\"postman login --with-api-key\");",
									"        pm.expect(response.text()).to.include(\"postman collection run\");",
									"    });",
									"});",
									"",
									""
								],
								"type": "text/javascript"
							}
						},
						{
							"listen": "prerequest",
							"script": {
								"exec": [
									""
								],
								"type": "text/javascript"
							}
						}
					],
					"request": {
						"auth": {
							"type": "apikey",
							"apikey": [
								{
									"key": "value",
									"value": "{{token}}",
									"type": "string"
								},
								{
									"key": "key",
									"value": "X-API-Key",
									"type": "string"
								},
								{
									"key": "in",
									"value": "header",
									"type": "string"
								}
							]
						},
						"method": "GET",
						"header": [
							{
								"key": "x-api-key",
								"value": "{{postman_api_key}}",
								"type": "text"
							}
						],
						"url": {
							"raw": "{{githubProjectUrl}}",
							"host": [
								"{{githubProjectUrl}}"
							]
						},
						"description": "It's time to check your work.\n\n1. **Get the Github project URL:** Go to your Github project and copy the project URL. The URL should look as follows: \\`[https://github.com/your-username/some-api-project/`](https://github.com/your-username/some-api-project%60)\n2. **Configure the collection:** Update the Postman collection variable \\`githubProjectUrl\\`with YOUR Github project URL. Make sure to configure both the \"Initial value\" and the \"Current value\".\n3. **Validate your solution**: Hit **Send** and look under the **Tests** tab of the server response at the bottom to review your test results. ENSURE ALL TESTS PASS.\n    \n\nIf you have any failures, review the failed test results or ask for support in the [community forum](https://community.postman.com/c/training/38). When all of your tests pass, move on to the next request in this folder."
					},
					"response": []
				}
			],
			"description": "Open the request \"Verify your work\" and follow the instructions in the request documentation."
		}
	],
	"event": [
		{
			"listen": "prerequest",
			"script": {
				"type": "text/javascript",
				"exec": [
					""
				]
			}
		},
		{
			"listen": "test",
			"script": {
				"type": "text/javascript",
				"exec": [
					""
				]
			}
		}
	],
	"variable": [
		{
			"key": "githubProjectUrl",
			"value": "https://github.com/avrutant/postman-api-automation/blob/main/.github/workflows/postman.yml",
			"type": "string"
		},
		{
			"key": "postman_api_key",
			"value": "",
			"type": "string"
		},
		{
			"key": "collection_uuid",
			"value": "",
			"type": "string"
		}
	]
}
